ALTER TABLE todo_item
      ADD COLUMN priority TINYINT DEFAULT 0 NOT NULL;

CREATE TABLE todo_view (
       VIEW_ID BIGINT IDENTITY,
       USER_ID BIGINT REFERENCES user(user_id),
       VIEW_NAME VARCHAR(32) NOT NULL
);

CREATE TABLE todo_view_lists (
       VIEW_ID BIGINT NOT NULL REFERENCES todo_view(view_id),
       TODO_LIST_ID BIGINT NOT NULL REFERENCES todo_list(todo_list_id),
       LIST_ORDER INT NOT NULL,
       PRIMARY KEY(VIEW_ID, TODO_LIST_ID)
) 

