(ns toto.view.icons)

(def img-arrow-blue [:i {:class "fa fa-lg fa-arrow-down icon-blue"}])
(def img-arrow-gray [:i {:class "fa fa-lg fa-arrow-down icon-gray"}])
(def img-bars [:i {:class "fa fa-bars icon-gray"}])
(def img-check [:i {:class "fa fa-check icon-black"}])
(def img-close-list [:i {:class "fa fa-times-circle fa-lg"}])
(def img-edit-list [:i {:class "fa fa-pencil icon-edit"}])
(def img-globe [:i {:class "fa fa-globe fa-lg icon-gray"}])
(def img-group [:i {:class "fa fa-group icon-gray"}])
(def img-restore [:i {:class "fa fa-repeat icon-black"}])
(def img-show-list [:i {:class "fa fa-bars fa-lg icon-bars"}])
(def img-star-gray [:i {:class "fa fa-lg fa-star-o icon-gray"}])
(def img-star-yellow [:i {:class "fa fa-lg fa-star icon-yellow"}])
(def img-trash [:i {:class "fa fa-trash-o icon-black"}])
(def img-window-close [:i {:class "fa fa-window-close-o icon-gray"}])
